config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :organizations do
    resources :histories
  end
  resources :services
  resources :forms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/structures' => "forms#structures"
  get '/structures/:id' => "forms#structure"
end

app/models/service.rb
class Service < ApplicationRecord
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:title, :icon, :text, :annual_price, :mandatory, :program)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :icon, class: "form-label" %>
    <%= form.text_field :icon, class:"form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :text, class: "form-label" %>
    <%= form.text_area :text, class:"form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :annual_price, class: "form-label" %>
    <%= form.text_field :annual_price, class:"form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :mandatory, class: "form-check-label" %>
    <%= form.check_box :mandatory, class:"form-check-input" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :program, class: "form-label" %>
    <%= form.text_field :program, class:"form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/services/_service.html.erb
<div id="<%= dom_id service %>">
  <p>
    <strong>Title:</strong>
    <%= service.title %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= service.icon %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= service.text %>
  </p>

  <p>
    <strong>Annual price:</strong>
    <%= service.annual_price %>
  </p>

  <p>
    <strong>Mandatory:</strong>
    <%= service.mandatory %>
  </p>

  <p>
    <strong>Program:</strong>
    <%= service.program %>
  </p>

</div>

app/views/services/edit.html.erb
<div class='page'>
  <div class='container forms'>
    <div class="structure-title">
      <h1>Editing Service</h1>
    </div>

    <%= render 'form', service: @service %>

    <%= link_to 'Show', @service, class: "btn btn-light min-width-btn" %> |
    <%= link_to 'Back', services_path, class: "btn btn-light min-width-btn" %>
  </div>
</div>

app/views/services/index.html.erb
<div class='page'>
  <div class='container forms'>
    <p id="notice"><%= notice %></p>

    <div class="structure-title">
      <h1>Services</h1>
    </div>

    <table class="table">
      <thead>
        <tr>
            <th>Title</th>
            <th>Icon</th>
            <th>Text</th>
            <th>Annual price</th>
            <th>Mandatory</th>
            <th>Program</th>
            <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @services.each do |service| %>
          <tr>
            <td><%= service.title %></td>
            <td><i class="bi bi-<%= service.icon %>"></i></td>
            <td><%= service.text %></td>
            <td><%= service.annual_price %></td>
            <td><%= service.mandatory %></td>
            <td><%= service.program %></td>
            <td><%= link_to 'Edit', edit_service_path(service) %></td>
            <td><%= link_to 'Destroy', service, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Service', new_service_path, class: "btn btn-success min-width-btn" %>

  </div>
</div>

app/views/services/new.html.erb
<div class='page'>
  <div class='container forms'>
    <div class="structure-title">
      <h1>New Service</h1>
    </div>

    <%= render 'form', service: @service %>

    <%= link_to 'Back', services_path, class: "btn btn-light min-width-btn" %>
  </div>
</div>

app/views/services/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

      <div class="form-group mb-3">
    <p><strong>Title:</strong></p>
    <div>
      <%= @service.title %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Icon:</strong></p>
    <div>
      <%= @service.icon %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Text:</strong></p>
    <div>
      <%= @service.text %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Annual price:</strong></p>
    <div>
      <%= @service.annual_price %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Mandatory:</strong></p>
    <div>
      <%= @service.mandatory %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Program:</strong></p>
    <div>
      <%= @service.program %>
    </div>
  </div>
  
  
  <%= link_to 'Edit', edit_service_path(@service), class: "btn btn-primary min-width-btn" %>
  <%= link_to 'Back', services_path, class: "btn btn-light min-width-btn" %>
</div>