config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :organizations do
    resources :histories
  end
  resources :services
  resources :forms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/structures' => "forms#structures"
  get '/structures/:id' => "forms#structure"
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :history
  after_create_commit { broadcast_append_later_to('invoices', invoice: self) }

  def price_provider
    price = self.history.price_diff_or_price(1)
    days = self.history.remaining_days.to_f
    (days*price/365).round(2)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to organization_url(@invoice.history.organization, anchor: 'factures'), 
                                  status: :see_other,
                                  notice: [{title: 'Modification effectuée', message: "La facture a été mise à jour", warning: false}] }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { redirect_to organization_url(@invoice.history.organization), 
                                  notice: [{title: 'Echec de la modification', message: "La facture n'a pas pu être mise à jour", warning: true}] }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:history_id, :price, :days, :invoiced, :invoiced_provider)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :history_id %>
    <%= form.text_field :history_id, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :price, class: "form-label" %>
    <%= form.text_field :price, class:"form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :days, class: "form-label" %>
    <%= form.number_field :days, class:"form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :invoiced, class: "form-check-label" %>
    <%= form.check_box :invoiced, class:"form-check-input" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :invoiced_provider, class: "form-check-label" %>
    <%= form.check_box :invoiced_provider, class:"form-check-input" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/invoices/_invoice.html.erb
<tr>
  <td><%= invoice.history&.date&.strftime("%d/%m/%Y") %></td>
  <td><%= invoice.days %></td>
  <td>
      <%= "#{invoice.price} €" %>
      <%= link_to invoice_path(invoice, invoice: {invoiced: !invoice.invoiced}),
                  class: "btn btn-sm btn-#{invoice.invoiced ? 'primary' : 'secondary'}",
                  data: {turbo_method: :patch} do %>
      <i class="bi bi-<%= invoice.invoiced ? 'check' : 'x' %>"></i> 
      <% end %>
  </td>
  <td>
      <%= "#{invoice.price_provider} €" %>
      <%= link_to invoice_path(invoice, invoice: {invoiced_provider: !invoice.invoiced_provider}),
                  class: "btn btn-sm btn-#{invoice.invoiced_provider ? 'primary' : 'secondary'}",
                  data: {turbo_method: :patch} do %>
      <i class="bi bi-<%= invoice.invoiced_provider ? 'check' : 'x' %>"></i> 
      <% end %>
  </td>
</tr>

app/views/invoices/edit.html.erb
<div class='page'>
  <div class='container forms'>
    <h1>Editing Invoice</h1>

    <%= render 'form', invoice: @invoice %>

    <%= link_to 'Show', @invoice, class: "btn btn-light min-width-btn" %> |
    <%= link_to 'Back', invoices_path, class: "btn btn-light min-width-btn" %>
  </div>
</div>

app/views/invoices/index.html.erb
<div class='page'>
  <div class='container forms'>
    <p id="notice"><%= notice %></p>

    <h1>Invoices</h1>

    <table class="table">
      <thead>
        <tr>
              <th>History</th>
              <th>Price</th>
              <th>Days</th>
              <th>Invoiced</th>
              <th>Invoiced provider</th>
              <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
                <td><%= invoice.history_id %></td>
                <td><%= invoice.price %></td>
                <td><%= invoice.days %></td>
                <td><%= invoice.invoiced %></td>
                <td><%= invoice.invoiced_provider %></td>
                <td><%= link_to 'Show', invoice %></td>
            <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
            <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Invoice', new_invoice_path, class: "btn btn-success min-width-btn" %>

  </div>
</div>

app/views/invoices/new.html.erb
<div class='page'>
  <div class='container forms'>
    <h1>New Invoice</h1>

    <%= render 'form', invoice: @invoice %>

    <%= link_to 'Back', invoices_path, class: "btn btn-light min-width-btn" %>
  </div>
</div>

app/views/invoices/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

      <div class="form-group mb-3">
    <p><strong>History:</strong></p>
    <div>
      <%= @invoice.history_id %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Price:</strong></p>
    <div>
      <%= @invoice.price %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Days:</strong></p>
    <div>
      <%= @invoice.days %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Invoiced:</strong></p>
    <div>
      <%= @invoice.invoiced %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Invoiced provider:</strong></p>
    <div>
      <%= @invoice.invoiced_provider %>
    </div>
  </div>
  
  
  <%= link_to 'Edit', edit_invoice_path(@invoice), class: "btn btn-primary min-width-btn" %>
  <%= link_to 'Back', invoices_path, class: "btn btn-light min-width-btn" %>
</div>