config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :organizations do
    resources :histories
  end
  resources :services
  resources :forms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/structures' => "forms#structures"
  get '/structures/:id' => "forms#structure"
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :organization
  has_one :invoice, :dependent => :delete

  def services
    self.services_ids&.split(',')&.map { |e| Service.find(e.to_i) } || []
  end

  def services_to_s
    services_line = ""
    services.each do |service|
      services_line << "#{service.program}, "
    end
    services_line[0,services_line.length-2]
  end

  def array_services_ids
    self.services_ids&.split(',')&.map { |e| e.to_i } || []
  end

  def annual_price(pu=1.4)
    price = self.quota ? (self.quota*pu).round(2) : 0
    self.services&.each do |service|
      price += service.annual_price
    end
    return price
  end

  def next
    self.class.unscoped.where("date >= ? AND id != ? AND organization_id=?", date, id, self.organization_id).order("date ASC").first
  end

  def previous
    self.class.unscoped.where("date <= ? AND id != ? AND organization_id=?", date, id, self.organization_id).order("date DESC").first
  end

  def price_diff(pu=1.4)
    previous_history = self.previous
    previous_history ? (self.annual_price(pu) - previous_history.annual_price(pu)).round(2) : 0
  end

  def price_diff_or_price(pu=1.4)
    price = self.annual_price(pu)
    price = price_diff if self.previous
    return price
  end

  def annual_price_with_diff(pu=1.4)
    diff = self.price_diff
    price = self.annual_price(pu).to_s
    if diff > 0
      price += " (+#{diff})"
    elsif diff < 0
      price += " (#{diff})"
    end
    price
  end

  def quota_diff
    previous_history = self.previous
    previous_history ? (self.quota - previous_history.quota) : 0
  end

  def quota_with_diff
    diff = quota_diff
    quota_string = self.quota.to_s
    if diff > 0
      quota_string += " (+#{diff})"
    elsif diff < 0
      quota_string += " (#{diff})"
    end
    quota_string
  end

  def remaining_days
    date_fin = Date.parse "#{self.date.year}-12-31"
    (date_fin-self.date).to_i
  end

end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: %i[ show edit update destroy ]
  before_action :set_organization


  # GET /histories or /histories.json
  def index
    @histories = @organization.histories
  end

  # GET /histories/1 or /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    prev = @organization.histories.last
    @history = History.new
    @history.organization_id = @organization.id
    @history.date = @organization.histories.last.date + 1
    @default_quota = prev ? prev.quota : 50
    @default_services = prev ? prev.services_ids : ''
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories or /histories.json
  def create
    prev = @organization.histories.last
    @history = History.new(history_params)
    @history.organization_id = @organization.id

    changes = false
    changes = true if @history.quota != prev.quota
    changes = true if @history.services_ids != prev.services_ids

      if changes
        if @history.save
          notice = [{title: "Création effectuée", 
                     message: "L'avenant est correctement enregistré"}]
          price = @history.price_diff_or_price
          if price > 0
            invoice = Invoice.new
            invoice.history_id = @history.id
            invoice.price = price
            invoice.days = @history.remaining_days
            if invoice.save
              redirect_to organization_histories_path, notice: notice.push(title: "Facture créée", 
                                                                           message: "La facture liée à cette avenant a bien été créée")
            else
              redirect_to organization_url(@organization), notice: notice.push(title: "Echec de la création de la facture", 
                                                                               message: "La facture liée à cette avenant n'a pas pu être créée",
                                                                               warning: true)
            end
          else
            redirect_to organization_path(@organization), notice: notice
          end
        else
          render :new, status: :unprocessable_entity
        end
      else
        redirect_to organization_url(@organization), notice: [{title: "Aucun changement détecté", 
                                                               message: "L'avenant n'a pas été créé", 
                                                               warning: true}]
      end
  end

  # PATCH/PUT /histories/1 or /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to histories_url, notice: "History was successfully updated." }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1 or /histories/1.json
  def destroy
    @history.destroy

    respond_to do |format|
      format.html { redirect_to histories_url, notice: "History was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    def set_organization
      @organization = Organization.find(params[:organization_id])
    end

    # Only allow a list of trusted parameters through.
    def history_params
      params.require(:history).permit(:organization_id, :quota, :services_ids, :comment, :date)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history, url: organization_histories_path(@organization.id)) do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>
      <ul>
        <% history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label "Date :", class: "form-label" %>
    <%= form.date_field :date, class:"form-control", required: true, min: (@organization.histories.last.date + 1) %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :quota, class: "form-label" %>
    <%= form.number_field :quota, class:"form-control", value: @default_quota %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :services_ids, class: "form-label" %>
    <%= form.text_field :services_ids, class:"form-control", value: @default_services %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :comment, class: "form-label" %>
    <%= form.text_area :comment, class:"form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit "Créer l'avenant", class: 'btn btn-primary' %>
    <%= link_to 'Annuler', organization_histories_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/histories/_histories.html.erb
<%= turbo_frame_tag 'histories' do %>
    <h5>
    Avenants
    <%= link_to new_organization_history_path(@organization) do %>
        <i class="bi bi-plus-square-fill"></i>
    <% end %>
    </h5>
    <table class="table table-striped table-sm align-middle">
        <thead>
        <tr>
                <th>Date</th>
                <th>Quota</th>
                <th>Services</th>
                <th>Tarif annuel</th>
                <th>Commentaires</th>
        </tr>
        </thead>
        <tbody>
        <% @organization.histories.order(:date).each do |history| %>
            <tr>
            <td><%= history.date&.strftime("%d/%m/%Y") %></td>
            <td><%= history.quota_with_diff %></td>
            <td><%= history.services_to_s %></td>
            <td><%= history.annual_price_with_diff %></td>
            <% unless history.comment.empty? %>
                <td class="comment"><i class="bi bi-file-text-fill btn btn-primary btn-sm" data-bs-toggle="tooltip" data-bs-placement="bottom" title="<%= history.comment %>"></i></td>
            <% else %>
                <td></td>
            <% end %>
            </tr>
        <% end %>
        </tbody>
    </table>
<% end %>

app/views/histories/_history.html.erb
<div id="<%= dom_id history %>">
  <p>
    <strong>Organization:</strong>
    <%= history.organization_id %>
  </p>

  <p>
    <strong>Quota:</strong>
    <%= history.quota %>
  </p>

  <p>
    <strong>Services:</strong>
    <%= history.services %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= history.comment %>
  </p>

</div>

app/views/histories/edit.html.erb
<div class='page'>
  <div class='container forms'>
    <h1>Editing History</h1>

    <%= render 'form', history: @history %>

    <%= link_to 'Show', @history, class: "btn btn-light min-width-btn" %> |
    <%= link_to 'Back', histories_path, class: "btn btn-light min-width-btn" %>
  </div>
</div>

app/views/histories/index.html.erb
<%= render 'histories' %>

app/views/histories/new.html.erb
<%= turbo_frame_tag 'histories' do %>
    <h5>Nouvel avenant</h5>
    <%= render 'form', history: @history %>
<% end %>

app/views/histories/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

      <div class="form-group mb-3">
    <p><strong>Organization:</strong></p>
    <div>
      <%= @history.organization_id %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Quota:</strong></p>
    <div>
      <%= @history.quota %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Services:</strong></p>
    <div>
      <%= @history.services_ids %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Comment:</strong></p>
    <div>
      <%= @history.comment %>
    </div>
  </div>
  
  
  <%= link_to 'Edit', edit_history_path(@history), class: "btn btn-primary min-width-btn" %>
  <%= link_to 'Back', histories_path, class: "btn btn-light min-width-btn" %>
</div>