config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :organizations do
    resources :histories
  end
  resources :services
  resources :forms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/structures' => "forms#structures"
  get '/structures/:id' => "forms#structure"
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :histories, :dependent => :delete_all
  has_many :invoices, through: :histories
  accepts_nested_attributes_for :histories, allow_destroy: true

  def actual_services
    self.histories.last&.services
  end

  def actual_services_ids
    self.histories.last&.array_services_ids
  end

  def first_account_complete
    "#{self.first_account}@#{self.domain}"
  end

  def contact
    "#{self.first_name} #{self.last_name}"
  end

  def actual_quota
    self.histories.last&.quota
  end

  def annual_price
    self.histories.last&.annual_price
  end

  def start_date
    self.histories.first&.date
  end

  #def invoices
  #  self.histories.map(&:invoice).compact
  #end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[ show edit update destroy ]
  before_action :set_services, only: %i[ show edit new]

  # GET /organizations or /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1 or /organizations/1.json
  def show
    @services_facultatifs = Service.where(mandatory: false)
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
    @organization.histories.build    
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations or /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        history = @organization.histories.last
        days = history.remaining_days
        Invoice.create history_id: history.id,
                       days: days,
                       price: (days * history.annual_price / 365).round(2) 
        notices = [{title: "Création effectuée", 
                   message: "Votre structure est correctement enregistrée"}]                                                  
        format.html { redirect_to organization_url(@organization), notice: notices }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1 or /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to organization_url(@organization), notice: "Organization was successfully updated." }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1 or /organizations/1.json
  def destroy
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url, notice: "Organization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    def set_services
      @services_inclus = Service.where(mandatory: true)
      @services_facultatifs = Service.where(mandatory: false)
      @min_date = Date.today+1
      @end_date = Date.parse("31/12/#{@min_date.year}")
      @nb_jours = (@end_date - @min_date).to_i
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization)
            .permit(:name, :address, :zip_code, :town, :first_name, :last_name, :email, :phone, :domain, :first_account,
                    histories_attributes: [:quota, :services_ids, :date, :comment])
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_with(model: @organization) do |form| %>

  <%= form.fields_for :histories do |history_subform| %>

    <div class="form-group mb-3">
        <div class="row g-3 align-items-center">
          <div class="col-auto">
            <%= form.label "Date d'ouverture souhaitée :", class: "form-label question" %>
          </div>
          <div class="col">
            <%= history_subform.date_field :date, class:"form-control", value: @min_date, min: @min_date, onchange: "update_relative_price();", required: true %>
          </div>
        </div>
    </div>

    <div class="form-group mb-3">
      <%= form.label "Nom de la structure :", class: "form-label question" %>
      <%= form.text_field :name, class:"form-control", required: true %>
    </div>

    <div class='question-separator'>
      Adresse postale :
    </div>

    <div class="form-group mb-3">
      <%= form.label "Adresse ( n°, rue, etc )", class: "form-label sub-question" %>
      <%= form.text_area :address, class:"form-control", required: true %>
    </div>

    <div class="form-group mb-3">
      <%= form.label "Code postal", class: "form-label sub-question" %>
      <%= form.text_field :zip_code, class:"form-control", required: true %>
    </div>

    <div class="form-group mb-3">
      <%= form.label "Ville", class: "form-label sub-question" %>
      <%= form.text_field :town, class:"form-control", required: true %>
    </div>

    <div class='question-separator'>
      Personne contact :
    </div>

    <div class="form-group mb-3">
      <%= form.label "Prénom", class: "form-label sub-question" %>
      <%= form.text_field :first_name, class:"form-control", required: true %>
    </div>

    <div class="form-group mb-3">
      <%= form.label "Nom", class: "form-label sub-question" %>
      <%= form.text_field :last_name, class:"form-control", required: true %>
    </div>

    <div class="form-group mb-3">
      <%= form.label "Courriel", class: "form-label sub-question" %>
      <%= form.text_field :email, class:"form-control", required: true %>
    </div>

    <div class="form-group mb-3">
      <%= form.label "Téléphone", class: "form-label sub-question" %>
      <%= form.text_field :phone, class:"form-control", required: true %>
    </div>

    <div class='question-separator'>
      Informations espace Zourit.net :
    </div>

    <div class="form-group mb-3">
      <%= form.label "Nom de domaine concerné :", class: "form-label sub-question" %>
      <%= form.text_field :domain, class:"form-control", placeholder: 'ex : monnomdedomaine.net', onchange: 'update_domain_name(this.value);', required: true %>
      <div class="question-desc">Si vous souhaitez "accrocher" vos mails à votre espace Zourit, une intervention sera nécessaire sur l'espace d'administration de votre domaine. Nous pouvons vous accompagner dans cette démarche (<a href="https://doc.zourit.net/admin/dns_zourit" target="_blank">documentation</a>).<br/>Si vous ne disposez pas de votre propre nom de domaine, nous pouvons vous proposer gratuitement un sous-domaine de la forme : votrenom.zourit.net</div>
    </div>

    <div class="form-group mb-3">
      <%= form.label "Premier compte à créer :", class: "form-label sub-question" %>
      <div class="input-group mb-3">
        <%= form.text_field :first_account, class:"form-control", required: true %>
        <span class="input-group-text" id="domain_name_span">@monnomdedomaine.net</span>
      </div>
      <div class="question-desc">L'accès à votre espace Zourit.net se fait via une adresse mail et un mot de passe. Cette adresse mail doit être une adresse du domaine que vous venez de nous communiquer. Merci de nous indiquer celle que vous souhaitez. Ex : contact@monnomdedomaine.net</div>
    </div>

    <div class="form-group mb-3">
      <%= form.label "Nombre de gigaoctets souhaités :", class: "form-label sub-question" %>
      <%= history_subform.number_field :quota, class:"form-control", min: 50, step: 10, onchange: "calcul_price();", required: true %>
      <div class="question-desc">Indiquez ici la taille globale demandée pour votre espace en Go. Elle ne peut être inférieure à 50 Go. Celle-ci pourra être révisée en cours d'année sur simple demande.</div>
    </div>

    <div class='question-separator'>
      Services de base inclus dans Zourit.net
    </div>

    <div class="question-desc">Les services de base sont automatiquement inclus dans votre abonnement Zourit.</div>

    <!-- Cards des services de base -->

    <div class="row">
    <% @services_inclus&.each do |service| %>
      <div class="col-sm-6 col-md-4 card-space">
        <div class="card">
          <div class="card-header">
            <i class="bi bi-<%= service[:icon] %> icons" aria-hidden="true"></i>
          </div>
          <div class="card-body">
            <p class='card-title'><%= service[:title] %></p>
            <p class="card-text"><%= service[:text] %></p>
            <p class='card-inclus'>inclus</p>
          </div>
        </div>
      </div>
    <% end %>
    </div>

    <!-- Fin des cards des services de base -->

    <div class='question-separator'>
      Services supplémentaires
    </div>

    <div class="question-desc">Certains services facultatifs peuvent être ajouté à vos services de base.</div>

    <!-- Cards des services facultatifs -->

    <div class="row">
      <% @services_facultatifs&.each do |service| %>
        <div class="col-sm-6 col-md-4 card-space">
          <div class="card">
            <div class="card-header">
              <i class="bi bi-<%= service[:icon] %> icons" aria-hidden="true"></i>
            </div>
            <div class="card-body">
              <p class='card-title'><%= service.title %></p>
              <p class='card-price'><%= service.annual_price>0.0 ? "+ #{service.annual_price} € par an" : "gratuit" %></p>
              <p class="card-text"><%= service.text %></p>
            </div>
            <div class="card-footer">
              <div class="form-group mb-3">
                <div class="form-check form-switch">
                  <% checked = @organization.actual_services.include?(service.id) %>
                  <%= hidden_field_tag "service[#{service.program.downcase}]", nil %>
                  <%= check_box_tag "service[#{service.program.downcase}]", '1', checked, onchange: "calcul_price();", class: "form-check-input services-facultatifs", data: {price: service.annual_price, id: service.id} %>
                  <%= form.label "activer ? ", class: "form-check-label" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <%= history_subform.hidden_field :services_ids %>
    </div>

    <!-- Fin des cards des services facultatifs -->

    <div class='question-separator'>
      Tarif
    </div>

    <div class="card mb-3">
      <div class="row g-0">
        <div class="col-md-4 card-header">
          <div class='calcultor-icon'>
          <i class="bi bi-calculator icons" aria-hidden="true"></i>
          </div>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="price-title">Total de votre abonnement à Zourit.net :</h5>
            <p class="card-text"><span id='annual_price'>70</span>€ TTC par an</p>
            <h5 class="price-title">Au prorata de l'année en cours :</h5>
            <p class="card-text">du <span id='start_date'></span> au <span id='end_date'><%= @end_date&.strftime("%d/%m/%Y") %></span>, soit <span id='nb_jours'></span> jours</p>
            <p class="card-text card-inclus">A régler pour l'année <span id="annee"></span> : <strong><span id='relative_price'></span>€ TTC</strong></p>
          </div>
        </div>
      </div>
    </div>
    
    <div class="form-group mb-3">
      <%= form.label "Informations complémentaires que vous souhaitez nous communiquer : ", class: "form-label sub-question" %>
      <%= history_subform.text_area :comment, class:"form-control" %>
    </div>

    <div class="form-check">
      <%= form.check_box :cgu, class: "form-check-input", required: true %>
      <p class="form-label sub-question">J'ai lu et accepté les <%= link_to 'conditions générale d\'utilisation', 'https://zourit.net/cgu/', target: '_blank' %></p>
    </div>

    <div class="form-group mb-3 submit">
      <%= form.submit 'Soumettre', class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

<script>
  function update_domain_name(val) {
    span = document.getElementById("domain_name_span");
    if (val!='') {
      span.innerText = '@' + val;
    } else {
      span.innerText = '@monnomdedomaine.net';
    }
  }

  function calcul_price(){
    prix_annuel = annual_price(1.4);
    annual_price_span = document.getElementById("annual_price");
    annual_price_span.innerText = annual_price(1.4);
    update_relative_price();
  }

  function annual_price(prix_go){
    const quota_form = document.getElementById("organization_histories_attributes_0_quota");
    let quota = quota_form.value;
    if (quota<50){ 
      quota = 50;
      quota_form.value = '50';
    }
    const services_ids_input = document.getElementById("organization_histories_attributes_0_services_ids");
    const services_facultatifs = document.getElementsByClassName("services-facultatifs");
    let services_ids = ""
    let prix_annuel = quota * prix_go;

    for (let i in services_facultatifs) {
      if (typeof services_facultatifs[i].dataset != 'undefined' && services_facultatifs[i].checked) {
        prix_annuel += parseFloat(services_facultatifs[i].dataset.price);
        services_ids += services_facultatifs[i].dataset.id + ",";
      }
    }
    services_ids_input.value = services_ids.slice(0, -1);
    return prix_annuel;
  }

  function update_relative_price(){
    prix_annuel = document.getElementById("annual_price").innerText;
    start_date_input = document.getElementById("organization_histories_attributes_0_date");
    const start_date = new Date(Date.parse(start_date_input.value));
    const annee = start_date.getFullYear();
    const end_date = new Date(Date.UTC(annee,11,31,0,0,0));
    days = nb_jours(start_date, end_date);
    document.getElementById("start_date").innerText = start_date.toLocaleDateString('fr-FR');
    document.getElementById("end_date").innerText = end_date.toLocaleDateString('fr-FR');
    document.getElementById("annee").innerText = annee;
    document.getElementById("nb_jours").innerText = days;
    prix_relatif = relative_price(prix_annuel, days);
    document.getElementById("relative_price").innerText = prix_relatif;
  }

  function nb_jours(start_date, end_date){
    diff = end_date.getTime() - start_date.getTime();
    nb = diff/(1000*60*60*24) + 1;
    return nb
  }

  function relative_price(prix_annuel, days){
    prix_relatif = Math.round(days*prix_annuel/365 * 100) / 100;
    return prix_relatif;
  }

  window.onload = calcul_price();  
</script>

app/views/organizations/_invoices.html.erb
<table class="table table-striped table-sm align-middle">
    <thead>
        <tr>
            <th>Date</th>
            <th>Jours (prorata)</th>
            <th>A facturer</th>
            <th>A facturer/prest</th>
        </tr>
    </thead>
    <tbody>
        <% invoices.each do |invoice| %>
            <tr>
                <td><%= invoice.history&.date&.strftime("%d/%m/%Y") %></td>
                <td><%= invoice.days %></td>
                <td>
                    <%= "#{invoice.price} €" %>
                    <%= link_to invoice_path(invoice, invoice: {invoiced: !invoice.invoiced}),
                                class: "btn btn-sm btn-#{invoice.invoiced ? 'primary' : 'secondary'}",
                                data: {turbo_method: :patch} do %>
                    <i class="bi bi-<%= invoice.invoiced ? 'check' : 'x' %>"></i> 
                    <% end %>
                </td>
                <td>
                    <%= "#{invoice.price_provider} €" %>
                    <%= link_to invoice_path(invoice, invoice: {invoiced_provider: !invoice.invoiced_provider}),
                                class: "btn btn-sm btn-#{invoice.invoiced_provider ? 'primary' : 'secondary'}",
                                data: {turbo_method: :patch} do %>
                    <i class="bi bi-<%= invoice.invoiced_provider ? 'check' : 'x' %>"></i> 
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/organizations/_organization.html.erb
<div id="<%= dom_id organization %>">
  <p>
    <strong>Name:</strong>
    <%= organization.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= organization.address %>
  </p>

  <p>
    <strong>Zip code:</strong>
    <%= organization.zip_code %>
  </p>

  <p>
    <strong>Town:</strong>
    <%= organization.town %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= organization.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= organization.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= organization.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= organization.phone %>
  </p>

  <p>
    <strong>Domain:</strong>
    <%= organization.domain %>
  </p>

  <p>
    <strong>First account:</strong>
    <%= organization.first_account %>
  </p>

</div>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization, class: "btn btn-light min-width-btn" %> |
<%= link_to 'Back', organizations_path, class: "btn btn-light min-width-btn" %>

app/views/organizations/index.html.erb
<h1>Structures</h1>

<table class="table table-striped">
  <thead>
    <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Zip code</th>
          <th>Town</th>
          <th>Domain</th>
          <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.start_date.strftime("%d/%m/%Y") %></td>
        <td><%= organization.zip_code %></td>
        <td><%= organization.town %></td>
        <td><%= organization.domain %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path, class: "btn btn-primary min-width-btn" %>

app/views/organizations/new.html.erb
<h1>Ouverture d'un espace</h1>

<%= render 'form', form: @form %>

app/views/organizations/show.html.erb
<div class="row">
  <div class="structure-title col-md-6 offset-md-3">
    <div class="input-group mb-3">
      <span class="input-group-text span-primary" id="domain_name_span"><i class="bi bi-building"></i></span>
      <div class="input-group-label"><div class="label">Structure</div><div class="data"><%= @organization.name %></div></div>
    </div>
  </div>

  <div class="structure-title col-md-6 offset-md-3">     
    <div class="input-group mb-3">
      <span class="input-group-text span-primary" id="domain_name_span"><i class="bi bi-mailbox2"></i></span>          
      <div class="input-group-memo">
        <div class="label">Adresse</div>
        <div><%= @organization.address %></div>
        <div><%= "#{@organization.zip_code} #{@organization.town}" %></div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="structure-contact col">
    <h5>Personne contact</h5>
    <div class="input-group mb-3">
      <span class="input-group-text span-primary" id="domain_name_span"><i class="bi bi-person-fill"></i></span>
      <div class="input-group-label"><div class="label">Nom du contact</div><div class="data"><%= @organization.contact %></div></div>
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text span-primary" id="domain_name_span"><i class="bi bi-envelope-fill"></i></span>
      <div class="input-group-label"><div class="label">Adresse email</div><div class="data"><%= @organization.email %></div></div>
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text span-primary" id="domain_name_span"><i class="bi bi-phone-fill"></i></span>
      <div class="input-group-label"><div class="label">Numéro de téléphone</div><div class="data"><%= @organization.phone %></div></div>
    </div>
  </div>
  <div class="structure-contact col">
    <h5>Domaine</h5>
    <div class="input-group mb-3">
      <span class="input-group-text span-primary" id="domain_name_span"><i class="bi bi-globe"></i></span>
      <div class="input-group-label"><div class="label">Nom de domaine</div><div class="data"><%= @organization.domain %></div></div>
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text span-primary" id="domain_name_span"><i class="bi bi-pie-chart-fill"></i></span>
      <div class="input-group-label"><div class="label">Quota</div><div class="data"><%= "#{@organization.actual_quota} Go" %></div></div>
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text span-primary" id="domain_name_span"><i class="bi bi-calendar-fill"></i></span>
      <div class="input-group-label"><div class="label">Ouverture le</div><div class="data"><%= "#{@organization.start_date&.strftime('%d/%m/%Y')}" %></div></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="structure-contact col">
    <h5>Services facultatifs</h5>       
    <div class="table-responsive">
      
      <div class="row row-check">
        <% ids = @organization.actual_services_ids %>
        <% @services_facultatifs.each do |service| %>
          <div class="col-4 card-space">
            <div class="card">
              <div class="card-header">
                <%= service[:program] %>
              </div>
              <% check = ids&.include?(service.id) ? 'check' : 'x' %>
              <div class="card-<%= check %>">
                <i class="bi bi-<%= check %>"></i>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="structure-contact col">
    <h5>Tarif</h5>
    <div class="input-group mb-3">
      <span class="input-group-text span-primary" id="domain_name_span"><i class="bi bi-calculator-fill"></i></span>
      <% actual_quota = @organization.actual_quota %>
      
      <div class="input-group-memo">
        <div class="label">Détail</div>
        <% if actual_quota %>
          <div><%= "#{actual_quota} Go x 1,4 = #{(actual_quota*1.4).round(2)} € par an" %></div>
        <% end %>          
      
        <% @organization.actual_services&.each do |service| %>   
          <% if service.annual_price > 0 %>
            <div><%= "+ #{service.program} à #{service.annual_price} € par an" %></div>
          <% end %>                     
        <% end %>
      </div> 
    </div>
      
    <div class="input-group mb-3">
      <span class="input-group-text span-primary" id="domain_name_span"><i class="bi bi-currency-euro"></i></span>
      <div class="input-group-label"><div class="label">Total annuel de</div><div class="data"><%= "= #{@organization.annual_price} €" %></div></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="structure-contact col">
    <%= render "histories/histories" %>
  </div>
</div>

<% invoices = @organization.invoices %>
<% if invoices.count>0 %>
  <div class="row">
    <div class="structure-contact col">
      <h5>Factures</h5>
      <%= render 'invoices', invoices: invoices %>
    </div>
  </div>
<% end %>

<div class="row align-items-start row-center">
  <div class="col">
    <%= link_to edit_organization_path, class: "btn btn-primary", type: "button" do %>
      <i class="bi bi-pencil-fill"></i>
      Modifier la structure
    <% end %>
  </div>
  <div class="col">
    <%= link_to new_organization_history_path(@organization), class: "btn btn-primary", type: "button" do %>
      <i class="bi bi-plus-square-fill"></i>
      Ajouter un avenant
    <% end %>
  </div>
  <div class="col">
    <%= link_to 'Retour', "/organizations", class: "btn btn-secondary", type: "button" %>
  </div>
</div>